### ISSUE TITLE
Не задано исключение для ошибки RuntimeException

### ISSUE THREAD

**Issue by Tor419** [xx029xx/javaqa-team-diplom#12]
# Описание
При запуске testErrorIfTheGameIsNotInstalled в классе PlayerTest, метод play который сообщает объекту-каталогу игр, откуда была установлена игра также надо обновить значения в мапе игрока, добавив проигранное количество часов возвращает суммарное количество часов, проигранное в эту игру. Если игра не была установлена, то надо выкидывать RuntimeException.Тест при неустановленной игре падает т.к. нет класса ошибки указывающего исключения.   

# Серьезность
Major

# Локация дефекта
https://github.com/xx029xx/javaqa-team-diplom/blob/717d1d8472217041a87a3d5914ed5dd968f01a48/src/test/java/ru/netology/PlayerTest.java#L143

# Шаги воспроизведения 
1. Открыть https://github.com/xx029xx/javaqa-team-diplom/blob/717d1d8472217041a87a3d5914ed5dd968f01a48/src/test/java/ru/netology/PlayerTest.java#L12 в IDEA
2. Запустить testErrorIfTheGameIsNotInstalled класса PlayerTest

*Ожидаемый результат:* testErrorIfTheGameIsNotInstalled проходит успешно. В логе отсутствуют ошибки
*Фактический результат:* testErrorIfTheGameIsNotInstalled падает с ошибкой:
org.opentest4j.AssertionFailedError: Expected java.lang.RuntimeException to be thrown, but nothing was thrown.

# Скриншот
![javaqa-team-diplom – PlayerTesnt java 2023-03-11 02](https://user-images.githubusercontent.com/119835408/224414354-cc986ab1-2719-4afa-853a-c059af5f8725.png)

# Окружение
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA Community Edition 2022.3.1
* **Java:** OpenJDK 11

**Comment by xx029xx** [comment]
Исправлено
