### ISSUE TITLE
Actual не соответствует expected в тесте testShouldShowTheGameThatWasPlayedMoreWithDifferentGenres

### ISSUE THREAD

**Issue by xx029xx** [xx029xx/javaqa-team-diplom#14]
# Описание
В тесте testShouldShowTheGameThatWasPlayedMoreWithDifferentGenres actual  не соответствует expected

# Локализация дефекта
https://github.com/xx029xx/javaqa-team-diplom/blob/227c8a9b410af8d2da17f9e88c12b9566ae45bed/src/test/java/ru/netology/PlayerTest.java#L67-L86

# Шаги воспроизведения

1.	Открыть [код программы](https://github.com/xx029xx/javaqa-team-diplom/blob/player/src/test/java/ru/netology/PlayerTest.java) в IDEA
2.	Запустить тест testShouldShowTheGameThatWasPlayedMoreWithDifferentGenres
3.	Посмотреть на вывод в консоли
*Ожидаемый результат:* Тест проходит
*Фактический результат:* Вывод сообщения  org.opentest4j.AssertionFailedError: 
Expected :ru.netology.Game@42637428
Actual   :ru.netology.Game@56078543

![Снимок1303](https://user-images.githubusercontent.com/120560334/224698473-a5e63c0f-9e86-4a5a-91c5-b819130f0bfb.JPG)

# Окружение:
* **IntelliJ IDEA 2022.3.1** (Community Edition)
* **Java:** OpenJDK 11

**Comment by Tor419** [comment]
Ошибка исправлена testShouldShowTheGameThatWasPlayedMoreWithDifferentGenres тест проходит.
