### ISSUE TITLE
В классе GameStore не отображается игра, добавленная через метод publishGame

### ISSUE THREAD

**Issue by xx029xx** [xx029xx/javaqa-team-diplom#2]
# Описание
При добавлении игры с помощью метода publishGame игра не добавляется 

# Локализация дефекта
https://github.com/xx029xx/javaqa-team-diplom/blob/026c90fdcde1f4c46bae13ae3be8bfe2eef71d3f/src/main/java/ru/netology/GameStore.java#L32-L39

# Шаги воспроизведения

1.	Открыть [код программы](https://github.com/xx029xx/javaqa-team-diplom/blob/026c90fdcde1f4c46bae13ae3be8bfe2eef71d3f/src/test/java/ru/netology/GameStoreTest.java) в IDEA
2.	Запустить тест shouldAddGame
3.	Посмотреть на вывод в консоли
*Ожидаемый результат:* Вывод сообщения  true, добавленная игра есть в каталоге
*Фактический результат:* Вывод сообщения  false, добавленной игры нет в каталоге

![скрин тест 1](https://user-images.githubusercontent.com/120560334/224248025-1d2a6612-e6c4-4a84-8b1d-9cce6564f7c8.JPG)

# Окружение:
* **IntelliJ IDEA 2022.3.1** (Community Edition)
* **Java:** OpenJDK 11

**Comment by Tor419** [comment]
Метод containsGame исправлен тест shouldAddGame проходит
