### ISSUE TITLE
Метод containsGame в классе GameStore не отображает игру, добавленную второй с помощью метода publishGame

### ISSUE THREAD

**Issue by xx029xx** [xx029xx/javaqa-team-diplom#3]
# Описание
При добавлении второй игры с помощью метода publishGame игра не добавляется 

# Локализация дефекта
https://github.com/xx029xx/javaqa-team-diplom/blob/026c90fdcde1f4c46bae13ae3be8bfe2eef71d3f/src/main/java/ru/netology/GameStore.java#L32-L39

# Шаги воспроизведения

1.	Открыть [код программы](https://github.com/xx029xx/javaqa-team-diplom/blob/026c90fdcde1f4c46bae13ae3be8bfe2eef71d3f/src/test/java/ru/netology/GameStoreTest.java) в IDEA
2.	Запустить тест shouldAddTwoGamesTest
3.	Посмотреть на вывод в консоли
*Ожидаемый результат:* Вывод сообщения  true, добавленная игра есть в каталоге
*Фактический результат:* Вывод сообщения  false, добавленной игры нет в каталоге

![скрин тест 2](https://user-images.githubusercontent.com/120560334/224256948-ed57c58f-2a74-41c5-9440-2c513cb2727a.JPG)

# Окружение:
* **IntelliJ IDEA 2022.3.1** (Community Edition)
* **Java:** OpenJDK 11

**Comment by Tor419** [comment]
Ошибка исправлена тест shouldAddTwoGamesTest проходит
