### ISSUE TITLE
Метод getMostPlayer возвращает нулевой массив в классе GameStore

### ISSUE THREAD

**Issue by xx029xx** [xx029xx/javaqa-team-diplom#4]
# Описание
В классе GameStore метод getMostPlayer при добавления одного игрока со временем 1 час через метод addPlayTime возвращает нулевой массив

# Локализация дефекта
https://github.com/xx029xx/javaqa-team-diplom/blob/026c90fdcde1f4c46bae13ae3be8bfe2eef71d3f/src/main/java/ru/netology/GameStore.java#L58-L69

# Шаги воспроизведения

1.	Открыть [код программы](https://github.com/xx029xx/javaqa-team-diplom/blob/026c90fdcde1f4c46bae13ae3be8bfe2eef71d3f/src/test/java/ru/netology/GameStoreTest.java) в IDEA
2.	Запустить тест shouldAddOneHourTest
3.	Посмотреть на вывод в консоли
*Ожидаемый результат:* Вывод сообщения  Игрок1
*Фактический результат:* Вывод сообщения null

![тест 4](https://user-images.githubusercontent.com/120560334/224258667-83299020-043a-4127-ba2e-73a0ef1f2361.JPG)

# Окружение:
* **IntelliJ IDEA 2022.3.1** (Community Edition)
* **Java:** OpenJDK 11

**Comment by Tor419** [comment]
Ошибка исправлена тест shouldAddOneHourTest проходит
