### ISSUE TITLE
Метод addPlayTime не суммирует время игры, в которую играл один игрок

### ISSUE THREAD

**Issue by xx029xx** [xx029xx/javaqa-team-diplom#5]
# Описание
Метод addPlayTime возвращает ошибочное значение, он не суммирует время игры, в которую играл один игрок, выводит сообщение с временем одной игры, не добавляя другое время игры

# Локализация дефекта
https://github.com/xx029xx/javaqa-team-diplom/blob/026c90fdcde1f4c46bae13ae3be8bfe2eef71d3f/src/main/java/ru/netology/GameStore.java#L46-L52

# Шаги воспроизведения

1.	Открыть [код программы](https://github.com/xx029xx/javaqa-team-diplom/blob/026c90fdcde1f4c46bae13ae3be8bfe2eef71d3f/src/test/java/ru/netology/GameStoreTest.java) в IDEA
2.	Запустить тест shouldAddNewHoursTest
3.	Посмотреть на вывод в консоли

*Ожидаемый результат:* Вывод сообщения Игрок1
*Фактический результат:* Вывод сообщения Игрок2
![тест 10](https://user-images.githubusercontent.com/120560334/224262399-de2015e1-ba1b-44b3-83f7-3728f5809ff0.JPG)

# Окружение:
* **IntelliJ IDEA 2022.3.1** (Community Edition)
* **Java:** OpenJDK 11

**Comment by Tor419** [comment]
Ошибка исправлена тест shouldAddNewHoursTest проходит.
