### ISSUE TITLE
Вместо количества времени проведенного за играми метод getSumPlayedTime возвращает нулевое значение

### ISSUE THREAD

**Issue by xx029xx** [xx029xx/javaqa-team-diplom#6]
# Описание
Метод getSumPlayedTime возвращает нулевое значение времени, проведенного за игрой, когда добавлен один игрок

# Локализация дефекта
https://github.com/xx029xx/javaqa-team-diplom/blob/026c90fdcde1f4c46bae13ae3be8bfe2eef71d3f/src/main/java/ru/netology/GameStore.java#L75-L78

# Шаги воспроизведения

1.	Открыть [код программы](https://github.com/xx029xx/javaqa-team-diplom/blob/026c90fdcde1f4c46bae13ae3be8bfe2eef71d3f/src/test/java/ru/netology/GameStoreTest.java) в IDEA
2.	Запустить тест shouldShowPlayedTimeOnePlayerTest
3.	Посмотреть на вывод в консоли

*Ожидаемый результат:* Вывод сообщения  5
*Фактический результат:* Вывод сообщения  0. Время игры не отображается

![тест 12](https://user-images.githubusercontent.com/120560334/224269505-69a64be9-4e1f-4e47-83fa-ad53b5197acb.JPG)

# Окружение:
* **IntelliJ IDEA 2022.3.1** (Community Edition)
* **Java:** OpenJDK 11

**Comment by Tor419** [comment]
Ошибка исправлена тест shouldShowPlayedTimeOnePlayerTest проходит.
