### ISSUE TITLE
Метод getSumPlayedTime не отображает общее количество времени игроков

### ISSUE THREAD

**Issue by xx029xx** [xx029xx/javaqa-team-diplom#7]
# Описание
Метод getSumPlayedTime возвращает ноль, вместо общего количества времени игроков, проведенным за играми, в классе GameStore

# Локализация дефекта
https://github.com/xx029xx/javaqa-team-diplom/blob/026c90fdcde1f4c46bae13ae3be8bfe2eef71d3f/src/main/java/ru/netology/GameStore.java#L75-L78

# Шаги воспроизведения

1.	Открыть [код программы](https://github.com/xx029xx/javaqa-team-diplom/blob/026c90fdcde1f4c46bae13ae3be8bfe2eef71d3f/src/test/java/ru/netology/GameStoreTest.java) в IDEA
2.	Запустить тест shouldShowPlayedTimeTest
3.	Посмотреть на вывод в консоли

*Ожидаемый результат:* Вывод сообщения 10. Общее количество времени игроков
*Фактический результат:* Вывод сообщения  0

![тест 13](https://user-images.githubusercontent.com/120560334/224277985-0a628ceb-db49-40c1-825c-a98a4361485b.JPG)

# Окружение:
* **IntelliJ IDEA 2022.3.1** (Community Edition)
* **Java:** OpenJDK 11

**Comment by Tor419** [comment]
Ошибка исправлена тест shouldShowPlayedTimeTest проходит.
