### ISSUE TITLE
Метод sumGenre класса Player возвращает ноль

### ISSUE THREAD

**Issue by Tor419** [xx029xx/javaqa-team-diplom#9]
# Описание
При запуске testShouldSumGenreIfOneGame в классе PlayerTest, метод SumGenre который принимает жанр игры (одно из полей объекта игры) и суммирует время, проигранное во все игры этого жанра этим игроком. Метод возвращает количество игроков 0 и тест падает. 

# Серьезность
Critical

# Локация дефекта
https://github.com/xx029xx/javaqa-team-diplom/blob/717d1d8472217041a87a3d5914ed5dd968f01a48/src/main/java/ru/netology/Player.java#L45

# Шаги воспроизведения 
1. Открыть https://github.com/xx029xx/javaqa-team-diplom/blob/717d1d8472217041a87a3d5914ed5dd968f01a48/src/test/java/ru/netology/PlayerTest.java#L12 в IDEA
2. Запустить testShouldSumGenreIfOneGame класса PlayerTest

*Ожидаемый результат:* testShouldSumGenreIfOneGame проходит успешно. В логе отсутствуют ошибки
*Фактический результат:* testShouldSumGenreIfOneGame падает с ошибкой: org.opentest4j.AssertionFailedError:
Expected :3
Actual :0

# Скриншот
![javaqa-team-diplom – PlayerTest java 2023-03-10 23](https://user-images.githubusercontent.com/119835408/224375449-98b36f6d-9247-4814-9f97-feae4c78a933.png)

# Окружение
* **Операционная система:** Windows 10 Pro
* **IDE:** IntelliJ IDEA Community Edition 2022.3.1
* **Java:** OpenJDK 11

**Comment by xx029xx** [comment]
Исправлено
